site_name: pyramid-flower
repo_url: https://github.com/tomascorrea/pyramid-flower
site_url: https://tomascorrea.github.io/pyramid-flower
site_description: Just a celery command to start flower with pyramid celery
site_author: Tomás Corrêa
edit_uri: edit/main/docs/
repo_name: tomascorrea/pyramid-flower
copyright: Maintained by <a href="https://tomascorrea.com">Florian</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append('../')
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tomascorrea/pyramid-flower
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/pyramid-flower

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
